kind: pipeline
name: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/open-beagle/cri-o

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: build-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/nix:2.3.16
    environment:
      BUILD_ARCH: amd64
    commands:
      - mkdir -p .dist
      - rm -rf /nix
      - cp -rfT ../nix /nix
      - cd .tmp/cri-o-v1.30.1
      - nix --print-build-logs --option cores 8 --option max-jobs 8 build --file nix/
      - cp -r result/bin ../../.dist/${BUILD_ARCH}

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/cri-o
      version: v1.30.1
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: build-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.22-arm64
    environment:
      BUILD_ARCH: arm64
    commands:
      - mkdir -p .dist
      - rm -rf /nix
      - cp -rfT .tmp/nix /nix
      - cd .tmp/cri-o-v1.30.1
      - rm -rf ./nix/default.nix
      - cd nix
      - ln -s default-arm64.nix default.nix
      - cd ..
      - nix --print-build-logs --option cores 8 --option max-jobs 8 build --file nix/
      - cp -r result/bin ../../.dist/${BUILD_ARCH}

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      repo: wod/cri-o
      version: v1.30.1
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry.cn-qingdao.aliyuncs.com/wod/cri-o:v1.30.1-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/cri-o:v1.30.1
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
